
["1) debug"]
	#
	#Set to true to enable logging on the ${log} channel.
	"Enable Logging" = true
	#
	#Set to true to enable debug mode
	debug = false

[core]
	#
	#Set to true to convert seeds only in the analyzer. Has no effect if "Override vanilla farming" is set to false.
	"Convert seeds only in analyzer" = false
	#
	#Set to true to allow mutations on clone events (spreading from single crop).
	"Clone mutations" = false
	#
	#Set to false if to disable triggering of mutations by using fertilizers on a cross crop.
	"Fertilizer mutations" = true
	#
	#Set this to true to have weeds destroy the crop sticks when they are broken with weeds (to encourage rake usage).
	"Weeds destroy crop sticks" = false
	#
	#The amount of seeds one seed bag can hold
	#Range: 8 ~ 256
	"seed bag capacity" = 64
	#
	#Set to false to disable the spreading of weeds
	"Weeds can spread" = true
	#
	#Set to false to disable planting of (agricraft) seeds outside crop sticks
	"Plant outside crop sticks" = true
	#
	#Defines the seed compost value, if set to zero, seeds will not be compostable
	#Range: 0.0 ~ 1.0
	"Seed compost value" = 0.3
	#
	#Set to false to disable certain animals eating certain crops (prevents auto-breeding)
	"animal attracting crops" = true
	#
	#Set to false to disable automatic JSON writeback.
	"Enable JSON write back" = true
	#
	#Set to true to allow only fertile plants to be able to cause, participate in, or contribute to a spreading / mutation action
	#(note that this may cause issues with obtaining some specific plants)
	"Only fertile crops mutate" = false
	#
	#Set to true to override vanilla farming, meaning vanilla seeds will be converted to agricraft seeds on planting.
	"Override vanilla farming" = true
	#
	#Set to false to disable mature weeds killing plants
	"Mature weeds kill plants" = true
	#
	#Enchantment cost in player levels to enchant the seed bag
	#Range: 0 ~ 30
	"seed bag enchant cost" = 10
	#
	#This is a global growth rate multiplier for crops planted on crop sticks.
	#Range: 0.0 ~ 3.0
	"Growth rate multiplier" = 1.0
	#
	#Set to true to completely disable the spawning of weeds
	"Disable weeds" = false
	#
	#Set to false if you wish to disable drops from raking weeds.
	"Raking weeds drops items" = true
	#
	#Set this to true to make only mature crops drop seeds (to encourage trowel usage).
	"Only mature crops drop seeds" = false
	#
	#Set to false to disable the generation of missing default jsons
	"Generate missing default JSONs" = true
	#
	#Set to false to disable collision boxes on crop sticks
	"Crop sticks collide" = true
	#
	#Set to false if AgriCraft loot modifiers are not allowed to reset grass drops (this overrides the "reset" property in the loot entries
	"Allow Grass Drop Resets" = true

["resource crops"]
	#
	#Set to false to disable the emerald nugget (in case resource crops are disabled, or alternatives are available
	"Enable emerald nugget" = true
	#
	#Set to false to disable the quartz nugget (in case resource crops are disabled, or alternatives are available
	"Enable quartz nugget" = true
	#
	#Set to false to disable the coal nugget (in case resource crops are disabled, or alternatives are available
	"Enable coal nugget" = true
	#
	#Set to false to disable the diamond nugget (in case resource crops are disabled, or alternatives are available
	"Enable diamond nugget" = true
	#
	#Set to false to disable the generation of resource crop jsons
	"Enable resource crop json generation" = true

[stats]
	#
	#Minimum allowed value of the Fertility stat (setting min and max equal will freeze the stat to that value in crop breeding)
	#Range: 1 ~ 10
	"Fertility stat min" = 1
	#
	#Set to true to hide the Mutativity stat (hidden stats will not show up in tooltips or seed analysis)
	#setting min and max equal and hiding a stat effectively disables it, with its behaviour at the defined value for min and max.
	"hide Mutativity stat" = false
	#
	#Minimum allowed value of the Mutativity stat (setting min and max equal will freeze the stat to that value in crop breeding)
	#Range: 1 ~ 10
	"Mutativity stat min" = 1
	#
	#Minimum allowed value of the Gain stat (setting min and max equal will freeze the stat to that value in crop breeding)
	#Range: 1 ~ 10
	"Gain stat min" = 1
	#
	#Logic to calculate stats from gene pairs, accepted values are: "min", "min", and "mean"
	"Stat calculation logic" = "max"
	#
	#Maximum allowed value of the Resistance stat (setting min and max equal will freeze the stat to that value in crop breeding)
	#Range: 1 ~ 10
	"Resistance stat max" = 10
	#
	#Minimum allowed value of the Growth stat (setting min and max equal will freeze the stat to that value in crop breeding)
	#Range: 1 ~ 10
	"Growth stat min" = 1
	#
	#Maximum allowed value of the Growth stat (setting min and max equal will freeze the stat to that value in crop breeding)
	#Range: 1 ~ 10
	"Growth stat max" = 10
	#
	#Set to true to hide the Growth stat (hidden stats will not show up in tooltips or seed analysis)
	#setting min and max equal and hiding a stat effectively disables it, with its behaviour at the defined value for min and max.
	"hide Growth stat" = false
	#
	#Maximum allowed value of the Strength stat (setting min and max equal will freeze the stat to that value in crop breeding)
	#Range: 1 ~ 10
	"Strength stat max" = 10
	#
	#Set to true to hide the Resistance stat (hidden stats will not show up in tooltips or seed analysis)
	#setting min and max equal and hiding a stat effectively disables it, with its behaviour at the defined value for min and max.
	"hide Resistance stat" = false
	#
	#Set to true to hide the Strength stat (hidden stats will not show up in tooltips or seed analysis)
	#setting min and max equal and hiding a stat effectively disables it, with its behaviour at the defined value for min and max.
	"hide Strength stat" = false
	#
	#Maximum allowed value of the Mutativity stat (setting min and max equal will freeze the stat to that value in crop breeding)
	#Range: 1 ~ 10
	"Mutativity stat max" = 10
	#
	#Maximum allowed value of the Fertility stat (setting min and max equal will freeze the stat to that value in crop breeding)
	#Range: 1 ~ 10
	"Fertility stat max" = 10
	#
	#Minimum allowed value of the Resistance stat (setting min and max equal will freeze the stat to that value in crop breeding)
	#Range: 1 ~ 10
	"Resistance stat min" = 1
	#
	#Maximum allowed value of the Gain stat (setting min and max equal will freeze the stat to that value in crop breeding)
	#Range: 1 ~ 10
	"Gain stat max" = 10
	#
	#Set to true to hide the Gain stat (hidden stats will not show up in tooltips or seed analysis)
	#setting min and max equal and hiding a stat effectively disables it, with its behaviour at the defined value for min and max.
	"hide Gain stat" = false
	#
	#Minimum allowed value of the Strength stat (setting min and max equal will freeze the stat to that value in crop breeding)
	#Range: 1 ~ 10
	"Strength stat min" = 1
	#
	#Set to true to hide the Fertility stat (hidden stats will not show up in tooltips or seed analysis)
	#setting min and max equal and hiding a stat effectively disables it, with its behaviour at the defined value for min and max.
	"hide Fertility stat" = false

[irrigation]
	#
	#Set to false to disable water tanks spawning a water block when broken when sufficiently full
	"Tanks spawn water block" = true
	#
	#Every loop, each unobscured plant in sprinkler range has this chance to get a growth tick from the sprinkler.
	#Range: 0.0 ~ 1.0
	"Sprinkler growth chance" = 0.2
	#
	#Defined in terms of mB per second. The irrigation loop progress will pause when there is insufficient water.
	#Range: 0 ~ 1000
	"Sprinkler water usage" = 10
	#
	#Configures the capacity (in mB) of one channel block
	#Range: 50 ~ 2000
	"Channel capacity" = 500
	#
	#Set to true to disable particles (Client only)
	"Disable particles" = false
	#
	#Configures the rate (in mB/t) at which tanks accrue water while raining (0 disables filling from rainfall)
	#Range: 0 ~ 50
	"Rain fill rate" = 5
	#
	#Configures the capacity (in mB) of one tank block
	#Range: 1000 ~ 40000
	"Tank capacity" = 8000
	#
	#The minimum number of ticks between successive starts of irrigation.
	#Range: 1 ~ 1200
	"Sprinkler growth interval" = 40

[decoration]
	#
	#When true, entities will be able to climb on grates
	"Grates always climbable" = true

[world]
	#
	#The minimum fraction of glass-type blocks a greenhouse ceiling needs in order to work (0.0 = none, 1.0 = all)
	#Be careful when modifying this value as it might break village greenhouses
	#Range: 0.0 ~ 1.0
	"Greenhouse ceiling glass fraction" = 0.65
	#
	#The maximum internal size of greenhouses, the larger this is, the longer greenhouse scans will take
	#Range: > 512
	"Greenhouse block size limit" = 512
	#
	#The growth rate modifier applied to crops inside greenhouses;
	#0 = no growth allowed (why would you do this), < 1 = slower growth, 1 = no effect, > 1 = faster growth
	#Range: 0.0 ~ 10.0
	"Greenhouse growth modifier" = 1.05
	#
	#The weight for spawning irrigated greenhouses in villages (set to 0 to disable spawning of irrigated greenhouses)
	#Range: 0 ~ 1000
	"Greenhouse spawn weight" = 10
	#
	#Set to false if greenhouses should not make crops ignore seasons
	"Greenhouses ignore seasons" = true

[compat]
	#
	#Set to false to disable compatibility with Create (in case things break)
	"Enable Create compat" = true
	#
	#Set to false if you want all mutations to be shown in JEI all the time instead of having to research them
	"Progressive JEI" = true
	#
	#Defines whether or not additional The One Probe data is rendered only when the magnifying glass is being used
	"TOP only with magnifying glass" = true
	#
	#Defines the mod controlling season logic in case multiple are installed
	#accepted values are: 
	"season logic" = "sereneseasons"
	#
	#Set to false to disable compatibility with Immersive Engineering (in case things break)
	"Enable Immersive Engineering compat" = true
	#
	#Set to false to disable compatibility with Blood Magic (in case things break)
	"Enable Blood Magic compat" = true
	#
	#Set to false to disable compatibility with Botany Pots (in case things break)
	"Enable Botany Pots compat" = true
	#
	#Set to false to disable weeds on Botany Pots
	"Enable Botany Pots weeds" = true
	#
	#Set to false to disable compatibility with Mystical Agriculture (in case things break)
	"Enable Mystical Agriculture compat" = true
	#
	#Set to false to disable compatibility with Straw Golem Reborn (in case things break)
	"Enable Straw Golem Reborn compat" = true
	#
	#Set to false to disable compatibility with Cyclic (in case things break)
	"Enable Cyclic compat" = true
	#
	#Set to false to disable compatibility with Industrial Foregoing (in case things break)
	"Enable Industrial Foregoing compat" = true
	#
	#Set to false to disable compatibility with Botania (in case things break)
	"Enable Botania compat" = true

[debug]
	#
	#Set to true to add Registry information to itemstack tooltips (Client only)
	"Registry tooltips" = false
	#
	#Set to true to add NBT information to itemstack tooltips (Client only)
	"NBT tooltips" = false
	#
	#Set to true to add Tag information to itemstack tooltips (Client only)
	"Tag tooltips" = false

[animations]
	#
	#Configures the animation duration in ticks for the camera to snap to the journal, 0 disables it (Client only)
	#Range: 0 ~ 40
	"Journal Animation Duration" = 10
	#
	#Configures the animation duration in ticks for the camera to snap to the seed analyzer, 0 disables it (Client only)
	#Range: 0 ~ 40
	"Seed Analyzer Animation Duration" = 15
	#
	#Determine if the journal and the analyzer use guis instead of in-world animation (Client only)
	"Use GUIs" = false

